SET client_min_messages = warning;

CREATE SEQUENCE customer_code_seq START 1001;
CREATE SEQUENCE invoice_number_seq START 1001;
CREATE SEQUENCE quote_number_seq START 1001;

CREATE FUNCTION create_invoice_number() RETURNS varchar
LANGUAGE sql AS $$
  SELECT 'INV-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('invoice_number_seq')::text, 6, '0')
$$;

CREATE TABLE roles (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(30) NOT NULL UNIQUE,
  description text
);

CREATE TABLE teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL UNIQUE,
  manager_id bigint,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id smallint NOT NULL REFERENCES roles(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  team_id bigint REFERENCES teams(id) ON DELETE SET NULL ON UPDATE CASCADE,
  manager_id bigint REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,  -- self reference
  name varchar(120) NOT NULL,
  email varchar(255) NOT NULL,
  password_hash text NOT NULL,
  phone varchar(30),
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_users_email CHECK (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  CONSTRAINT chk_users_manager_not_self CHECK (manager_id IS NULL OR manager_id <> id)
);
CREATE UNIQUE INDEX uq_users_email ON users (lower(email)) WHERE deleted_at IS NULL;

ALTER TABLE teams ADD CONSTRAINT fk_teams_manager
  FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE lead_sources (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(60) NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  score_weight smallint NOT NULL DEFAULT 5 CHECK (score_weight BETWEEN 0 AND 30)
);
CREATE TABLE lead_statuses (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(60) NOT NULL UNIQUE,
  sort_order int NOT NULL DEFAULT 0,
  is_final boolean NOT NULL DEFAULT false,
  color varchar(20) NOT NULL DEFAULT '#6366f1'
);
CREATE TABLE lead_stages (          
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(60) NOT NULL UNIQUE,
  probability smallint NOT NULL CHECK (probability BETWEEN 0 AND 100),
  sort_order int NOT NULL DEFAULT 0
);
CREATE TABLE tags (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL UNIQUE,
  color varchar(20) NOT NULL DEFAULT '#8b5cf6'
);

CREATE TABLE customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_code varchar(20) NOT NULL UNIQUE DEFAULT ('CUS-' || lpad(nextval('customer_code_seq')::text, 5, '0')),
  company_name varchar(200) NOT NULL,
  email varchar(255),
  phone varchar(30),
  address text,
  city varchar(100),
  country varchar(100),
  industry varchar(100),
  website varchar(200),
  status varchar(20) NOT NULL DEFAULT 'active',
  account_owner bigint REFERENCES users(id) ON DELETE SET NULL,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_customers_status CHECK (status IN ('active','inactive','prospect','churned')),
  search_vector tsvector GENERATED ALWAYS AS (
    to_tsvector('simple'::regconfig, coalesce(company_name,'') || ' ' || coalesce(email,'') || ' ' || coalesce(city,'') || ' ' || coalesce(notes,''))
  ) STORED
);
CREATE UNIQUE INDEX uq_customers_email ON customers (lower(email)) WHERE email IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE ON UPDATE CASCADE,
  name varchar(120) NOT NULL,
  email varchar(255),
  phone varchar(30),
  designation varchar(120),
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
-- composite unique: contact email is unique inside one customer
CREATE UNIQUE INDEX uq_contacts_customer_email ON contacts (customer_id, lower(email)) WHERE email IS NOT NULL AND deleted_at IS NULL;
-- only one primary contact per customer
CREATE UNIQUE INDEX uq_contacts_one_primary ON contacts (customer_id) WHERE is_primary AND deleted_at IS NULL;

-- ---------- Leads ----------
CREATE TABLE leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id int NOT NULL REFERENCES lead_sources(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  status_id int NOT NULL REFERENCES lead_statuses(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  assigned_to bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  name varchar(150) NOT NULL,
  email varchar(255),
  phone varchar(30),
  company_name varchar(200),
  priority varchar(10) NOT NULL DEFAULT 'medium',
  estimated_value numeric(14,2) NOT NULL DEFAULT 0,
  score smallint NOT NULL DEFAULT 0,
  notes text,
  converted_customer_id bigint REFERENCES customers(id) ON DELETE SET NULL,
  converted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_leads_priority CHECK (priority IN ('low','medium','high','urgent')),
  CONSTRAINT chk_leads_value CHECK (estimated_value >= 0),
  CONSTRAINT chk_leads_score CHECK (score BETWEEN 0 AND 100),
  search_vector tsvector GENERATED ALWAYS AS (
    to_tsvector('simple'::regconfig, coalesce(name,'') || ' ' || coalesce(company_name,'') || ' ' || coalesce(email,'') || ' ' || coalesce(notes,''))
  ) STORED
);

CREATE TABLE lead_tags (            -- many-to-many junction
  lead_id bigint NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  tag_id int NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (lead_id, tag_id)
);

-- ---------- Activities / Follow-ups / Tasks ----------
CREATE TABLE activities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id bigint REFERENCES leads(id) ON DELETE CASCADE,
  customer_id bigint REFERENCES customers(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  type varchar(20) NOT NULL,
  subject varchar(200) NOT NULL,
  notes text,
  activity_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_activities_type CHECK (type IN ('call','meeting','email','note','other')),
  CONSTRAINT chk_activities_target CHECK (lead_id IS NOT NULL OR customer_id IS NOT NULL)
);

CREATE TABLE follow_ups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id bigint REFERENCES leads(id) ON DELETE CASCADE,
  customer_id bigint REFERENCES customers(id) ON DELETE CASCADE,
  assigned_to bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  title varchar(200) NOT NULL DEFAULT 'Follow-up',
  due_at timestamptz NOT NULL,
  reminder_at timestamptz,
  status varchar(20) NOT NULL DEFAULT 'open',
  notes text,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_followups_status CHECK (status IN ('open','completed','cancelled')),
  CONSTRAINT chk_followups_target CHECK (lead_id IS NOT NULL OR customer_id IS NOT NULL),
  CONSTRAINT chk_followups_reminder CHECK (reminder_at IS NULL OR reminder_at <= due_at)
);

CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assigned_to bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_by bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  lead_id bigint REFERENCES leads(id) ON DELETE SET NULL,
  customer_id bigint REFERENCES customers(id) ON DELETE SET NULL,
  title varchar(200) NOT NULL,
  description text,
  priority varchar(10) NOT NULL DEFAULT 'medium',
  due_date date,
  status varchar(20) NOT NULL DEFAULT 'todo',
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_tasks_priority CHECK (priority IN ('low','medium','high','urgent')),
  CONSTRAINT chk_tasks_status CHECK (status IN ('todo','in_progress','completed','cancelled'))
);

-- ---------- Products / Opportunities / Quotes ----------
CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(150) NOT NULL,
  sku varchar(40) NOT NULL UNIQUE,
  description text,
  category varchar(60),
  price numeric(14,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE opportunities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  lead_id bigint REFERENCES leads(id) ON DELETE SET NULL,
  owner_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  stage_id int NOT NULL REFERENCES lead_stages(id) ON DELETE RESTRICT,
  title varchar(200) NOT NULL,
  amount numeric(14,2) NOT NULL DEFAULT 0,
  products_total numeric(14,2) NOT NULL DEFAULT 0,      -- maintained by trigger
  probability smallint,
  expected_close_date date,
  closed_at timestamptz,
  lost_reason text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_opp_amount CHECK (amount >= 0),
  CONSTRAINT chk_opp_probability CHECK (probability IS NULL OR probability BETWEEN 0 AND 100)
);

CREATE TABLE opportunity_products (
  opportunity_id bigint NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity int NOT NULL CHECK (quantity > 0),
  unit_price numeric(14,2) NOT NULL CHECK (unit_price >= 0),
  discount numeric(5,2) NOT NULL DEFAULT 0 CHECK (discount BETWEEN 0 AND 100),
  PRIMARY KEY (opportunity_id, product_id)             -- composite unique
);

CREATE TABLE quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_number varchar(30) NOT NULL UNIQUE DEFAULT ('QT-' || lpad(nextval('quote_number_seq')::text, 6, '0')),
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  opportunity_id bigint REFERENCES opportunities(id) ON DELETE SET NULL,
  status varchar(20) NOT NULL DEFAULT 'draft',
  valid_until date,
  total_amount numeric(14,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  notes text,
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_quotes_status CHECK (status IN ('draft','sent','accepted','rejected','expired'))
);

-- ---------- Invoices / Payments ----------
CREATE TABLE invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  opportunity_id bigint REFERENCES opportunities(id) ON DELETE SET NULL,
  invoice_number varchar(30) NOT NULL UNIQUE DEFAULT create_invoice_number(),
  issue_date date NOT NULL DEFAULT current_date,
  due_date date NOT NULL,
  total_amount numeric(14,2) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'sent',
  notes text,
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_invoices_amount CHECK (total_amount >= 0),
  CONSTRAINT chk_invoices_dates CHECK (due_date >= issue_date),
  CONSTRAINT chk_invoices_status CHECK (status IN ('draft','sent','partial','paid','overdue','cancelled'))
);

CREATE TABLE payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  amount numeric(14,2) NOT NULL CHECK (amount > 0),
  payment_method varchar(20) NOT NULL DEFAULT 'bank_transfer',
  status varchar(20) NOT NULL DEFAULT 'successful',
  paid_at timestamptz NOT NULL DEFAULT now(),
  reference varchar(100),
  notes text,
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_payments_method CHECK (payment_method IN ('cash','bank_transfer','card','cheque','online')),
  CONSTRAINT chk_payments_status CHECK (status IN ('successful','pending','failed','refunded'))
);
CREATE UNIQUE INDEX uq_payments_invoice_reference ON payments (invoice_id, reference) WHERE reference IS NOT NULL;

-- ---------- History / Audit ----------
CREATE TABLE lead_status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id bigint NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  old_status_id int REFERENCES lead_statuses(id) ON DELETE SET NULL,
  new_status_id int NOT NULL REFERENCES lead_statuses(id) ON DELETE RESTRICT,
  changed_by bigint REFERENCES users(id) ON DELETE SET NULL,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  table_name varchar(60) NOT NULL,
  record_id bigint,
  action varchar(20) NOT NULL,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_audit_action CHECK (action IN ('INSERT','UPDATE','DELETE','SOFT_DELETE'))
);
